name: zeazn_invest_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  another_flushbar: ^1.12.30
  confetti: ^0.8.0
  country_code_picker: ^3.3.0
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  envied: ^1.1.1
  equatable: ^2.0.7
  ffmpeg_kit_flutter_new: ^2.0.0
  file_picker: ^10.1.2
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_mlkit_text_recognition: ^0.15.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  pdfx: ^2.9.1
  pinput: ^5.0.1
  redacted: ^1.0.13
  video_compress: ^3.1.4
  video_player: ^2.9.5

dev_dependencies:
  build_runner: ^2.4.15 # build generated files
  envied_generator: ^1.1.1 # obfuscate credentials
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/fonts/Epilogue-Light.ttf
          weight: 300
        - asset: assets/fonts/Epilogue-Regular.ttf
          weight: 400
        - asset: assets/fonts/Epilogue-Medium.ttf
          weight: 500
        - asset: assets/fonts/Epilogue-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Epilogue-Bold.ttf
          weight: 700
        - asset: assets/fonts/Epilogue-ExtraBold.ttf
          weight: 800
